/*
 * my-bpf-sensor - User-space loader for the CO-RE eBPF program
 *
 * This program loads the BPF object file using libbpf's CO-RE support.
 * It uses the BPF skeleton generated from bpf_program.bpf.c.
 */

#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <signal.h>
#include <syslog.h>
#include <bpf/libbpf.h>
#include <bpf/bpf.h>
#include "bpf_program.skel.h"  /* Generated by bpftool or libbpf-gen */

static volatile int keep_running = 1;

void handle_signal(int sig) {
    if (sig == SIGTERM || sig == SIGINT) {
        keep_running = 0;
    }
}

/* Callback for ring buffer events */
int handle_event(void *ctx, void *data, size_t len) {
    struct exec_event {
        __u32 pid;
        __u32 uid;
        char comm[16];
    } *e = data;

    syslog(LOG_INFO, "BPF event: pid=%u uid=%u comm=%s", e->pid, e->uid, e->comm);
    printf("EXEC: pid=%u uid=%u comm=%s\n", e->pid, e->uid, e->comm);
    return 0;
}

int main(int argc, char *argv[]) {
    struct my_bpf_sensor_bpf *skel = NULL;
    struct ring_buffer *rb = NULL;
    struct sigaction sa;
    int err;

    openlog("my-bpf-sensor", LOG_PID | LOG_NDELAY, LOG_DAEMON);
    syslog(LOG_INFO, "my-bpf-sensor starting (CO-RE eBPF loader)");

    /* Set up signal handling */
    memset(&sa, 0, sizeof(sa));
    sa.sa_handler = handle_signal;
    sigaction(SIGTERM, &sa, NULL);
    sigaction(SIGINT, &sa, NULL);

    /* Open and load BPF object using CO-RE skeleton */
    skel = my_bpf_sensor_bpf__open();
    if (!skel) {
        syslog(LOG_ERR, "Failed to open BPF skeleton. No BTF support?");
        fprintf(stderr, "ERROR: Failed to open BPF skeleton. "
                        "Ensure the kernel supports BTF (CONFIG_DEBUG_INFO_BTF=y).\n");
        goto cleanup;
    }

    err = my_bpf_sensor_bpf__load(skel);
    if (err) {
        syslog(LOG_ERR, "Failed to load BPF skeleton: %d", err);
        fprintf(stderr, "ERROR: Failed to load BPF program. "
                        "CO-RE relocation may have failed.\n");
        goto cleanup;
    }

    err = my_bpf_sensor_bpf__attach(skel);
    if (err) {
        syslog(LOG_ERR, "Failed to attach BPF skeleton: %d", err);
        goto cleanup;
    }

    syslog(LOG_INFO, "BPF program attached successfully. Monitoring exec events...");

    /* Set up ring buffer to consume events */
    rb = ring_buffer__new(bpf_map__fd(skel->maps.exec_events),
                          handle_event, NULL, NULL);
    if (!rb) {
        syslog(LOG_ERR, "Failed to create ring buffer");
        goto cleanup;
    }

    /* Main loop: poll ring buffer every 200ms */
    while (keep_running) {
        err = ring_buffer__poll(rb, 200 /* timeout ms */);
        if (err < 0) {
            syslog(LOG_ERR, "Ring buffer poll error: %d", err);
            break;
        }
    }

cleanup:
    if (rb)
        ring_buffer__free(rb);
    if (skel) {
        my_bpf_sensor_bpf__detach(skel);
        my_bpf_sensor_bpf__destroy(skel);
    }
    syslog(LOG_INFO, "my-bpf-sensor shutting down");
    closelog();
    return 0;
}